FTG-38 | Add inventory item pick up
SzymCrusader/FTG pull request #25
Opened 2023-03-06 00:21 UTC by SaronTetra

2023-03-18 23:54 UTC, SzymCrusader requested changes

2023-03-18 23:54 UTC, SzymCrusader commented on core/inventory/inventory_item.gd
> +var created = false
unused variable

2023-03-18 23:54 UTC, SzymCrusader commented on core/inventory/inventory_item.gd
> +	$Sprite2D/Debug.text = str(item_stack)
unused

2023-03-18 23:54 UTC, SzymCrusader commented on core/inventory/slot.gd
> +@onready var inventory_item_scene = preload("res://core/inventory/inventory_item.tscn")
unused

2023-03-18 23:54 UTC, SzymCrusader commented on ui/hotbar.gd
> +		Events.hotbar_selected.emit()
something happens?

2023-03-18 23:55 UTC, SaronTetra commented on ui/hotbar.gd
> +		Events.hotbar_selected.emit()
right, missing `emit(12)`

2023-03-19 00:07 UTC, SzymCrusader approved these changes

2023-03-19 00:08 UTC, merged